### ISSUE TITLE
Simultaneous solve for phase-only and complex-2x2 with different intervals

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/CubiCal#219]
Simultaneously solving for phases on a short interval and amplitudes on a longer interval is a nice trick that MeqTrees offers. I tried this in CubiCal as follows:

```
[ga]
_Help = Options for G-Jones term
label = G
solvable = True
type = complex-2x2
load-from =
xfer-from =
save-to = {data[ms]}/{JONES}-field_{sel[field]}-ddid_{sel[ddid]}.parmdb
dd-term = 0
fix-dirs =
diag-diag = False
update-type = full
time-int = 60
freq-int = 171
max-prior-error = 0.1
max-post-error = 0.1
clip-low = 0.1
clip-high = 10.0
clip-after = 5
max-iter = 20
conv-quorum = 0.99
ref-ant = None
prop-flags = default
_Templated = True

[gp]
_Help = Options for G-Jones term
label = Gp
solvable = True
type = phase-diag
load-from =
xfer-from =
save-to = {data[ms]}/{JONES}-field_{sel[field]}-ddid_{sel[ddid]}.parmdb
dd-term = 0
fix-dirs =
diag-diag = False
update-type = full
time-int = 4
freq-int = 171
max-prior-error = 0.1
max-post-error = 0.1
clip-low = 0.1
clip-high = 10.0
clip-after = 5
max-iter = 20
conv-quorum = 0.99
ref-ant = None
prop-flags = default
_Templated = True
```

with `--sol--jones = Ga,Gp`, But it bailed out with:

```
Solver for tile 0 chunk D0T0F0 failed with exception: only complex-2x2 terms can be made solvable in a Jones chain
```

Is this simply not feasible? It doesn't look like there's a CASA-style way to add a pre-computed gain table on the fly, and calibrating on CORRECTED_DATA feels a bit weird...

Cheers.

**Comment by JSKenyon** [comment]
This is supported, but not using the parameterized solvers i.e. anything other than complex 2x2. The reason for this is that the parameterized solvers make the Jones chain mathematics far less elegant and it is questionable how efficient the result would be. That being said, I have learned a great deal since the original incarnation of the Jones chain solver, so there is perhaps hopes that support for parameterised terms will be added in the future. 

In the meantime, your request has been anticipated (sort of) and you can get the behaviour you want by defining both Jones terms as complex 2x2 and then set the update type on one of them to phase-diag. The full list of available update types is [here](https://cubical.readthedocs.io/en/latest/parset.html), under --gainterm-update-type.

**Comment by IanHeywood** [comment]
Perfect, thanks!
