### ISSUE TITLE
revise --out-name naming and backup scheme to avoid invasive renaming 

### ISSUE THREAD

**Issue by SpheMakh** [ratt-ru/CubiCal#289]
When running cubical in a directory that also happens to the output directory of cubical outputs it is not ideal for cubical move my files (created by cubical or not) outside of the said directory.  In fact, it would be much better to just raise an exception saying I should either specify `--overwrite` or change the `--out-name`. Failing that Cubical should definitely not be creating files outside the working directory unless specified by the user (see [this line](https://github.com/ratt-ru/CubiCal/blob/master/cubical/main.py#L212)), better to have a backup folder in the working directory.

**Comment by bennahugo** [comment]
This is working under the valid assumption that the user has RW access in the base folder from where they are going to start the run (ie. if they are in abc and specify out-name to be output/run1 then they better have access to abc for temporary files. I suggest you change your working directory to output and out-name to run1 in this case @SpheMakh

**Comment by bennahugo** [comment]
https://github.com/SpheMakh/Stimela/issues/415 is the root of this problem. I agree there should be an additional check to see whether the base folder can be moved and a nicer warning printed and stop called if it can't, but this is a good default to have.

**Comment by bennahugo** [comment]
the proposed idea by @KshitijT  to clobber by default in stimela risks overwriting previous gain solutions by a novice user.

**Comment by bennahugo** [comment]
(having been down that road myself quite a few times....)

**Comment by o-smirnov** [comment]
The real culprit is this line: https://github.com/ratt-ru/CubiCal/blob/master/cubical/main.py#L193 together with this one: https://github.com/ratt-ru/CubiCal/blob/master/cubical/main.py#L211

If ``--output-name`` does not contain an explicit directory component, then we assume the user wants to create all output files under their current working directory. In this case, the attempt to rename the directory is misguided and ill-advised -- CubiCal should just go ahead and clobber files. 

My preferred workflow is to make an output directory for cubical products, since there are now quite a few, and this keeps them neat and organized. And I quite like the auto-renaming behaviour, because indeed it protects novice users and confused professors from shooting themselves in the foot, as @bennahugo noted. In the scenario where we use a separate output directory...

On the other hand, it does now occur to me that auto-renaming can be antisocial and confusing. If a novice user specifies ``--out-name /home/user/my_project/cc-out``, they certainly don't expect ``my_project`` to be renamed under them!

I guess there's two different scenarios:

* the user wants the outputs going into a separate "CubiCal output folder" that's meant for CubiCal and CubiCal only. In this case, the auto-renaming of older output folders is quite useful.

* the user wants the outputs going into a directory that's meant for other things besides CubiCal. In this case the renaming is absolutely evil.

Perhaps the default logic should be, CubiCal is only allowed to rename if CubiCal itself created the folder in the first place?

**Comment by bennahugo** [comment]
or allow only relative paths to CWD (and have another parameter for that) in out-name

**Comment by bennahugo** [comment]
(which is the behaviour I always assumed)

**Comment by o-smirnov** [comment]
Relative or absolute doesn't make a difference though -- in the second scenario above, the user could be trying to specify a relative path to a non-CubiCal-generated folder...

**Comment by SpheMakh** [comment]
I think Einstein was thinking of a case like this when he said, "Everything should be made as simple as possible, but not simpler"

**Comment by bennahugo** [comment]
so copy only output/basename* in this case into a unique old folder relative to CWD

**Comment by o-smirnov** [comment]
As the Russian saying goes, simplicity can be worse than thievery...

**Comment by o-smirnov** [comment]
It also strongly reminds me of the joke about the gorilla catchers.

**Comment by SpheMakh** [comment]
Poor people like us, who work on pipelines, depend on predetermined paths for output products, so having the output directory that you specify changed by a task is catastrophic. Whereas, an optional backup folder inside the output directory is ok, and maybe even desirable for debugging.

**Comment by KshitijT** [comment]
> It also strongly reminds me of the joke about the gorilla catchers.

What is the joke about gorilla catchers ?!?!

**Comment by o-smirnov** [comment]
Remind me when we're at the Rat...

**Comment by bennahugo** [comment]
So I guess the quickest way to modify the current backup solution is to write a cookie into the output folder if cubical created it and check for said cookie when deciding if it should move and backup. Otherwise stop and print 'Output directory already exists, but has been created by a 3rd party. Will not override.'

**Comment by bennahugo** [comment]
The users can then specify a unique name for their output directory in OUTPUT=... in stimela

**Comment by o-smirnov** [comment]
Yeah, I like cookies...

**Comment by SpheMakh** [comment]
Changing a user-specified output folder is not necessary. Why not just create a backup folder in the CWD, then have `cubical-backup-1, cubical-backup-2` and just move cubical outputs there? 

Why the insistence on this clearly flawed approach?

**Comment by SpheMakh** [comment]
If you want to keep old runs but lack the foresight to change `--out-name` then you get the old runs moved to a backup folder that cubical creates in the CWD.

**Comment by o-smirnov** [comment]
> Why not just create a backup folder in the CWD, then have cubical-backup-1, cubical-backup-2 and just move cubical outputs there?

You mean move actual files, one by one? I think that'd be even more fraught with potential fuck-ups. And how's sneakily moving files better than sneakily renaming folders?

**Comment by o-smirnov** [comment]
I think there may be two separate arguments here:

(a) what's the most sensible and robust default behaviour for a novice or stupid user 

(b) what's the most sensible and robust behaviour for a tool in the pipeline

One is not necessarily the same as the other...

**Comment by o-smirnov** [comment]
...but to satisfy (b), a pipeline developer can bake in some non-default option settings that would give him the desired behaviour, right?

So, one suggestion would be: ``--out-clobber never|always|backup``. Default is ``backup`` (and then it tries to be clever in ways we have yet to converge on). But inside your cab, you could set it to ``always`` and then you know that there's no funny business going on, ever.

**Comment by bennahugo** [comment]
I agree with @o-smirnov on (b) with the exception of the cab default = 'never'. Together with the cookie trick the bare-metal default can be 'backup'. I would rather have a pipeline fall over before overwriting  logs and tables by accident.

**Comment by KshitijT** [comment]
@bennahugo , I would say that once there is a pipeline, a user is not going to worry too much about re-running it again and again, at least if they do, they'll do it with different output folders ? 
I would rather the pipeline ran through than have the user come back and check where it fell over and find it crashed not because of some fundamental issues with data reduction, but because Cubical didn't want to overwrite output products. 
This is only in a pipeline scenario, where you have sort of decided to go with a blackbox, rather than reducing the data manually.
Of course, when reducing the data not through an impersonal pipeline and trying to figure out what's going wrong with my data reduction, I would deeply appreciate cubical not overwriting my previous run.
In the end, if having `overwrite=True` in Stimela cab is too much,we can just write the MeerKATHI worker with `overwrite=True`, but as @SpheMakh  points out Stimela **is** a pipelining tool - even for something like pybdsm, Stimela has `clobber=True` to ensure that the cab doesn't fall over - even though that's not the default in pybdsm itself.

**Comment by SpheMakh** [comment]
Sensible behaviour would be to either raise an exception if output products exist or overwrite them. Backing up outputs from previous runs should be optional and not the default behaviour. 

> You mean move actual files, one by one? I think that'd be even more fraught with potential fuck-ups. And how's sneakily moving files better than sneakily renaming folders?

My thinking is that if you want to be sneaky, then do it in the least invasive way possible. In this case, simply moving cubical outputs (cubical should know all the files it creates, so it moving them shouldn't be difficult) to a folder clearly labelled as a backup folder (`cubical.old` or `cubical.backup`) seems less invasive than renaming a user-specified output or working directory.

**Comment by SpheMakh** [comment]
> (a) what's the most sensible and robust default behaviour for a novice or stupid user

Raise an exception if output products already exist. Then tell the user to either change `--out-name` for every run or enable `--out-backup` if they want to keep data from previous runs.

**Comment by JSKenyon** [comment]
For what it is worth, and I think this is just reiterating what @SpheMakh has said, I think all output should go in an output folder with some sensible default name. Thereafter, subsequent runs should move all non-folder contents of output to output/backups/sensibly_named_folder. We could even go a step further and compress backup outputs, putting them at output/backups/sensible_name.tar.gz. There can still be an overwrite=True option, in which case the contents of output may be overwritten, but this way we can protect novices, minimise output bloat and avoid bad behaviour in a pipeline context. That being said, I may have missed the point, so feel free to correct me.

**Comment by o-smirnov** [comment]
> In this case, simply moving cubical outputs (cubical should know all the files it creates, so it moving them shouldn't be difficult) 

This "simply" may not be that simple (remember what happened to the last "simple"?) The set of outputs it creates (e.g. plots, tables and such) can vary depending on what settings it ran with. Maybe it produced G tables, maybe it produced B and dE tables. Maybe this plot, maybe that plot, depending on what the user asked for. It can even depend on what the data itself looks like (there can be more flagging plots, or fewer).

So if your output folder is full of files from an older run, what does CubiCal decide to back up? It **can't** know what the older run produced exactly, because the settings could have been different. The best it can then do is to move away each older file before writing to it, which scatters extra complexity throughout the code.... and results in an output folder with, potentially, a mix of older and newer products. I fear this would be even more confusing than the current scheme.

(This is why I much prefer the workflow with a dedicated "CubiCal only" output folder. One CubiCal run, one folder, no confusion, no ambiguity...)

Anyway, we can and should keep on arguing about sensible defaults, but for the pipeline you ought to be able to pin down the specific behaviour. Maybe it's even "simpler" (ha ha!) to have two boolean options:

``--out-overwrite 0|1``: are we allowed to overwrite outputs quietly, or do we raise an error.

``--out-backup 0|1``: do we monkey around with backups, or not.

Or do we go with a three-way ``--out-clobber never|always|backup`` option?

**Comment by bennahugo** [comment]
I vote for 3 with folders. Include a sensible message if the output folder was created with something else (e.g. stimela). The user can then set the default behaviour in their pipelines to whatever they want - at their own peril. clobber or not should be left to whoever writes the stimela script.

**Comment by o-smirnov** [comment]
> (This is why I much prefer the workflow with a dedicated "CubiCal only" output folder. One CubiCal run, one folder, no confusion, no ambiguity...)

On reflection, I **really** want to promote this workflow by default, in the least invasive way. So how about:

(a) ``--out-name foo`` implies an output folder of ``foo.cc-out``, and a default filename prefix of ``cc``.

(b) ``--out-name foo.cc-out/cc`` is a longhand way of saying the same

(c) ``--out-name bar/`` (note trailing slash) explicitly names the folder, so we use ``bar/cc*`` for filenames

(d) ``--out-name bar/prefix`` explicitly names ``bar/prefix*``

If the resulting folder is named ``*.cc-out``, CubiCal treats it as "private property", i.e. it's allowed to create it if it doesn't exist, and to back up an already existing one. If it's not named ``cc-out``, then we treat it as "public property" i.e. no monkey business.

And we keep an ``--out-overwrite 0|1`` (default 0) option, as a last line of defence against clobbering things uninitentionally.

**Comment by JSKenyon** [comment]
@o-smirnov I think you last set of suggestions seems sensible, although I worry that the trailing slash differentiating between a) and c) may be a bit subtle. This may seem simple enough to us, but I suspect it will trip users up. 

The other idea I though might work is to generate a cubical prefix/suffix using the date and time at which the run began. That way it doesn't matter what output you produced, you only need to know the prefix/suffix. Additionally, it is then very clear which output is new and which is old. That being said, this might make like more challenging for subsequent pipeline steps that then depend on file names generated at runtime.

**Comment by o-smirnov** [comment]
> although I worry that the trailing slash differentiating between a) and c) may be a bit subtle. 

We could forbid (c) and throw an error. The user must then explicitly specify both folder name and prefix.

> The other idea I though might work is to generate a cubical prefix/suffix using the date and time

Sensible people like @IanHeywood already use this scheme for pretty much everything... but we already support it! Try ``--out-name "{DATE}{TIME}-foo"``. There's a substitution scheme through which many config settings are passed [here](https://github.com/ratt-ru/CubiCal/blob/master/cubical/main.py#L52).

**Comment by o-smirnov** [comment]
OK, after much ado and religious fighting, we've agreed on most things except one (binary) choice. So the current consensus is:

(a) Stupid user mode, specify output folder (``--out-dir cubical`` default) and name prefix (``--out-name cc`` default) separately. Dirname is implicitly suffixed with ``.cc-out``, but the less-stupid user can add a trailing slash to avoid this. It is expected that the command-line user will primarily use ``--out-dir`` to name their output folders.

(b) Pipeline mode. If ``--out-name`` contains slashes, we assume it is a full output path & name prefix, and ignore the ``--out-dir`` setting (a message can be printed to this effect)

On top of that, two options:

* ``--out-overwrite 0|1``, default is 0. Allow overwriting of existing output, or throw an exception. 

* ``--out-backup 0|1``. Allow backing up of existing output folder (only relevant, in (a) when ``--out-dir`` is employed). Discussion of default has prompted a jihad, so I've postponed it until everyone's had a few drinks.

**Comment by KshitijT** [comment]
Going to miss this issue and all the fun discussions ! 😿
