### ISSUE TITLE
P Jones is doubly applied when using montblanc

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/CubiCal#301]
The changes introduced by @o-smirnov in the polcal branch doubly applies P Jones to sky model when montblanc is used, because montblanc internally applies P Jones.

This is already fixed on my branch

**Comment by o-smirnov** [comment]
OK hang on the parset defines two independent options: ``--model-pa-rotate`` and ``--montblanc-pa-rotate``, this is perhaps misguided and needs to be defined more consistently.

The issue the two options are meant to resolve arises when we combine LSMs with MODEL_DATA. The latter may be in the sky frame or the antenna frame. DATA can be in the sky frame or the antenna frame. So Montblanc itself needs options to turn PA on or off, so that MODEL_DATA and LSMs are evaluated in the same frame.

This is getting confusing, so perhaps we should try to list the use cases on this issue.
