### ISSUE TITLE
Can't seem to disable feed rotation (P-Jones)

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/CubiCal#312]
As per the title, I have:

```
--out-derotate = 0
--model-feed-rotate = auto
--model-pa-rotate = 0
--montblanc-pa-rotate = None
```

but it's proceeding anyway:

```
 - 16:23:21 - data_handler       [39.0/43.3 49.2/49.2 15.0Gb] reading MODEL_DATA
 - 16:48:35 - parallactic_machin [30.5/62.0 41.9/66.4 23.9Gb] Applying P Jones to sky (precomputed)
 - 17:01:58 - solver             [60.5/73.4 62.3/76.3 23.9Gb] D0T0F0 (end solve) G: 20 iters, conv 75.00%, d/fl 1.61%, PGE 0.0243, stall 96.30%, chi^2 1.38 -> 0.5
49 (0.6953), noise 0.255 -> 0.223
 - 17:03:46 - parallactic_machin [38.8/77.6 50.4/79.6 28.4Gb] Applying P Jones to sky (precomputed)
```

**Comment by IanHeywood** [comment]
Trying with `--model-feed-rotate = 0` at @o-smirnov's suggestion.

**Comment by o-smirnov** [comment]
Just to clarify, there's time-variable PA rotation, and there's a static feed rotation following the FEED_ANGLE entry in the MS, and both are administered via a P-Jones.

I think your initial set of options disables the former but leaves the latter in place.

(Arguably, we could add an optimization for a static rotation of 90/270 degrees -- since that's just a swap of X with Y -- and I bet that's all it's doing there. It's a bit wasteful to compute that via a full-blown rotation matrix...)

**Comment by IanHeywood** [comment]
Gotcha, thanks chief. Just trying to shave this off the run-time.

**Comment by bennahugo** [comment]
> Arguably, we could add an optimization for a static rotation of 90/270 degrees -- since that's just a swap of X with Y -- and I bet that's all it's doing there. It's a bit wasteful to compute that via a full-blown rotation matrix...

This would be wrong because it flips the sign of Q. I think we need to remove the X/Y flip options in everything including DDF.

**Comment by o-smirnov** [comment]
> This would be wrong because it flips the sign of Q. I think we need to remove the X/Y flip options in everything including DDF.

Yeah I mean swap and change signs/conjugate appropriately. Still a much faster operation that applying two rotation matrices explicitly.
