### ISSUE TITLE
Overzealous flagging  and the unexpected application of bad bitflags 

### ISSUE THREAD

**Issue by JSKenyon** [ratt-ru/CubiCal#35]
This is the primary reason for discrepancies between MeqTrees and CubiCal. Cubical needs an option to prevent flags being saved. We should also verify that flags don't get raised unnecessarily. 

Additionally, if cubical raises flags, the FLAG and FLAGROW columns will be repopulated using ALL the flagsets in the MS. This is potentially dangerous if a particular flagset is bad - my D147 test case was flagging 84% of the data. Either we must make it clear that this is happening and rely on the user to repopulate FLAG and FLAGROW as desired, or we should provide an option which allows the user to specify which flagsets are combined into FLAG/FLAGROW after CubiCal is done.

**Comment by o-smirnov** [comment]
OK I see the problem finally. When writing out the cubical bitflag, it was ORing the flag into the existing bit directly (rather than clearing the bit first). Thus, all previous cubical-raised flags -- those inadvertently raised in a bad previous run, for example -- remained in effect, and got propagated into FLAG/FLAG_ROW.

Interestingly, it was correctly ignoring previous cubical flags -- so you could see a legitimate solution converging, yet still find everything flagged in the output.

Easy, minor fix -- PR on the way.
