### ISSUE TITLE
need to honour no_beam tag for LSM sources

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#431]
The tigger LSM format allows for a ``no_beam`` tag on sources, which is an indicator that the source is given in apparent flux units, and no beam should be applied. This is not currently honoured by Montblanc. A quick kludge may be required. @JSKenyon @ulricharmel @sjperkins

**Comment by JSKenyon** [comment]
If my memory serves, Montblanc doesn't really have a mechanism for doing different things per source. I think the only way around this will be be to cluster each direction into a beam required group and no beam group. Each group will need to be predicted separately (much like the directions), one with the FitsBeamSourceProvider and one without. The results would need to be accumulated into the relevant direction.

**Comment by JSKenyon** [comment]
Just so that this is documented somewhere:

![nobeamcomp](https://user-images.githubusercontent.com/6582745/106714699-e6063180-6604-11eb-8554-194153ac6290.png)

Images made with identical parameters. G at (1,1), dE at (64, 32). Left image is current master (nobeam not honoured), right image is with the issue-431 PR (nobeam honoured). Performance was virtually identical (PR was actually slightly faster).

@ulricharmel you can try the issue-431 branch when you have a moment. May interest you too @o-smirnov!

**Comment by ulricharmel** [comment]
@JSKenyon sure I will

**Comment by ulricharmel** [comment]
@JSKenyon I tested it on the C-MS. I think your patch is doing the right. I get similar and expected results.
