### ISSUE TITLE
complex-2x2 gain machine & kernel : cycompute_corrected function

### ISSUE THREAD

**Issue by ulricharmel** [ratt-ru/CubiCal#91]
Hi. 
I was trying to understand something and found my self looking at the code for applying the computed gains to the observed visibilities.  

for d in xrange(n_dir):
        for t in xrange(n_tim):
            rr = t/t_int
            for f in xrange(n_fre):
                rc = f/f_int
                for aa in xrange(n_ant):
                    for ab in xrange(n_ant):
                        corr[t,f,aa,ab,0,0] = \
                        g[d,rr,rc,aa,0,0]*o[t,f,aa,ab,0,0]*gh[d,rr,rc,ab,0,0] 

This is a piece of the code. I am confused with this. I don't think this will apply the gains correctly when n_dir is > 1. I think ***corr*** should be initialised to ***o*** before the loops and ***o*** replaced by ***corr*** in the loops. Else we will just apply the gains of the last direction to the observed visibilities

**Comment by JSKenyon** [comment]
In truth, it is impossible to correct the observed data when n_dir>1 anyway. You are correct - this may indeed have peculiar behaviour and I will take a look at it. The thing to realise is that the observed data can never be indexed by d.

**Comment by o-smirnov** [comment]
Yeah exactly, there's no "corrrecting" for a DD-gain. Best you can do is pick a direction. I believe the sensible thing to do is to correct for d=0. Or make an ``i_dir=0`` keyword argument, to pick a direction.

As written, that kernel is very inefficient, since it loops over d needlessly, and just ends up applying the last direction only. So it needs a small fix.

If you look at ``jones_chain.apply_inv_gains()``, you can see that it only applies the DI terms of the chain.

**Comment by ulricharmel** [comment]
Yeah I see. I was very puzzled, I am little bit disappointed DD calibration does not "fully" or "properly" exist. At-least they way I thought of it.
